### ISSUE TITLE
Mismatch IK / FK solutions for dh parameter with non-zero EEF offset

### ISSUE THREAD

**Issue by JonathanKuelz** [OstermD/EAIK#11]
I am still investigating the reason, but I just cam across the following inconsistency:

1. I have some DH parameters that define a robot. I manually compute the joint frames from the DH parameters and create an EAIK Robot (the `IK_Homogeneous` implementation).
2. I compute a reachable goal (using my own code).
3. I try to solve the IK problem by calling `robot.IK`
4. I get conflicting result (see attached image)

Problems with the results I get:
(1) is the eaik robot's forward kinematics of the Q I obtain from the IK method
(2) is the "goal pose" I wanted to solve the IK for
(3) is the forward kinematics in my own implementation, using the Q I got from EAIK
(4) is the forward kinematics of another EAIK robot (from `IK_DH`), using the Q I obtained

All of them have matching orientation, and all of them should be equal. However, only (3) and (4) are. This means that the forward and inverse kinematics of the original robot do not overlap.

Another result: If I use the dh-robot, it works. I get correct IK results.

Currently, there's no action required, I need to figure out what went wrong on my end. Maybe I can close this issue as soon as I did, maybe not, lets see.

![image](https://github.com/user-attachments/assets/32dabfe5-0ebd-4412-b9ff-ca10dcfd1764)

**Comment by OstermD** [comment]
One thing I'd do is to check if the used solution is actually analytical or an LS solution.
As far as I can see, you are currently using the first solution in the obtained Q vector.
Note the order of solutions does not correspond to their accuracy/validity.
The usual procedure is to filter for non-LS solutions first.

If no analytic version was obtained, you'd then need to sort the LS solutions by the metric you are looking for - this could, for one, be the standard Euclidian distance between the desired and actual pose, the difference between the joint angles to your previous pose (e.g., when following a trajectory) or something else.

Especially for wrist-partitioned robots, it is common to obtain LS solutions that are "perfect" with respect to orientation but are quite off in position (or the other way around).

However, the mismatch between the forward kinematics of IK_Homogeneous and IK_DH seems weird.
I will look into that, as we're anyways missing some unit tests on the Python part of this project (which, in this case, converts the poses to our angle-axis + axis offset representation)

**Comment by JonathanKuelz** [comment]
What does "quite off" mean? Quite off in the sense of larger numerical issues? Or could it explain offsets in the area of tens of centimeters (for industry-sized robots with arm length ~1.5m)?

Regarding DH / Homogeneous mismatch, I believe I will be able to find the reason, I just needed some time to expose kinematics to the python side to continue debugging, see latest commit in #10

**Comment by JonathanKuelz** [comment]
As expected, the problem seems to be related with the non-zero EEF offset. For both robots, the DH and the homogeneous one, the joint axes are equal, and only the points P differ. Still need to figure out if the mistake is in my computation of the EEF frame or in the EAIK one:

![image](https://github.com/user-attachments/assets/d30ce3b1-ed8e-4778-b030-bda6352da4c3)

**Comment by OstermD** [comment]
> What does "quite off" mean? Quite off in the sense of larger numerical issues? Or could it explain offsets in the area of tens of centimeters (for industry-sized robots with arm length ~1.5m)?
> 
> Regarding DH / Homogeneous mismatch, I believe I will be able to find the reason, I just needed some time to expose kinematics to the python side to continue debugging, see latest commit in #10

If analytical solutions exist (i.e., any solution is marked with LS=False), then the remaining LS solutions can be considered as invalid. They resemble a path in the "solution tree" where one subproblem's extraenous solution was used and has basically no geometrical interpretation -> the error can be well in the order of centimeters or even more.

Basically every analytically solvable run is guaranteed to yield these invalid solutions.
Flagging these solutions as invalid is another thing we can add.

If however no analytical solution exists, then all subproblem solutions must be considered as valid.
It is good practice to then only take the one with the smallest error metric.

**Comment by OstermD** [comment]
> Here's some code to reproduce my issues - maybe you can find the misconception or the error based on this @OstermD
> 
> ```
> import numpy as np
> 
> from eaik.IK_DH import Robot as dh_robot
> from eaik.IK_Homogeneous import Robot as hom_robot
> 
> def dh_forwards(alpha, a, d, theta):
>     result = np.eye(4)
>     all_frames = list()
>     assert alpha.shape == a.shape == d.shape == theta.shape
>     st = np.sin(theta)
>     ct = np.cos(theta)
>     sa = np.sin(alpha)
>     ca = np.cos(alpha)
>     for i in range(len(alpha)):
>         offset = np.array([
>             [ct[i], -st[i] * ca[i], st[i] * sa[i], a[i] * ct[i]],
>             [st[i], ct[i] * ca[i], -ct[i] * sa[i], a[i] * st[i]],
>             [0, sa[i], ca[i], d[i]],
>             [0, 0, 0, 1]
>         ])
>         result = result @ offset
>         all_frames.append(result.copy())
>     return result, all_frames
> 
> alpha_test = np.array([-1.5707964, -1.5707964,  1.5707964, -1.5707964, -1.5707964, 1.5707964])
> a_test = np.array([0., 0.00508904, 0., 0., 0., 0.8681647 ])
> d_test = np.array([0., 0.11531961, 0.45735025, 0.16493249, 0., 0.7245597 ])
> q0 = np.zeros(6)
> 
> manual_fk, frames = dh_forwards(alpha_test, a_test, d_test, q0)
> 
> # DH parameters are defined s.t. the frames returned by the function above are "at the end" of the current link
> # We implicitly assume that the first joint is placed in the world frame
> # The last frame is interpreted as the EEF frame in EAIK, thus we need to insert the world frame (0th joint) at the beginning
> frames.insert(0, np.eye(4))
> rob_dh = dh_robot(alpha_test, a_test, d_test)
> rob_hom = hom_robot(np.stack(frames))
> 
> print("DH robot:", rob_dh.fwdKin(q0).round(4))
> print("Homogeneous robot:", rob_hom.fwdKin(q0).round(4))
> print("Manual forwards kinematics", manual_fk.round(4))
> ```

The issue to this was a faulty calculation of the static end effector offset in the Python class. 
#13  should resolve this issue.

Please reopen this issue if this is not the case for you

**Comment by JonathanKuelz** [comment]
Just realized the issue is not resolved. The above test still fails for random q's

**Comment by JonathanKuelz** [comment]
My bad - your fix works, I just hadn't adapted my test correctly
